Name:           ros-hydro-segbot-simulation-apps
Version:        0.3.1
Release:        0%{?dist}
Summary:        ROS segbot_simulation_apps package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/segbot_simulation_apps
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-hydro-bwi-msgs
Requires:       ros-hydro-bwi-planning-common
Requires:       ros-hydro-bwi-tools
Requires:       ros-hydro-gazebo-msgs
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-multi-level-map-msgs
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-tf
BuildRequires:  boost-devel
BuildRequires:  ros-hydro-bwi-msgs
BuildRequires:  ros-hydro-bwi-planning-common
BuildRequires:  ros-hydro-bwi-tools
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-gazebo-msgs
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-multi-level-map-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-roslaunch
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-tf

%description
Applications designed specifically to be used in a simulation environment, such
as opening and closing doors inside the building simulation.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Mar 31 2015 Piyush Khandelwal <piyushk@gmail.com> - 0.3.1-0
- Autogenerated by Bloom

* Tue Mar 24 2015 Piyush Khandelwal <piyushk@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

